gen sdb

diff --git a/.github/workflows/generate.yaml b/.github/workflows/generate.yaml
--- a/.github/workflows/generate.yaml
+++ b/.github/workflows/generate.yaml
@@ -174,6 +174,14 @@ jobs:
           bash "${{ matrix.script }}"
         continue-on-error: true
 
+      - name: Exit if failed
+        run: |
+          if [[ "${META_GEN}" == "FAILED" ]]; then
+             echo -e "\n[X] FATAL: Failed to Generate Metadata"
+            exit 1
+          fi
+        continue-on-error: false
+        
       - name: Get DateTime & Purge files (=> 95 MB)
         run: |
           #Presets
